// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    return $("input[type=text]").not(".keep-enabled").attr("disabled", "disabled").css({
      "color": "black"
    });
  });

}).call(this);
